# Site settings
title: Patrick Kirby personal website
description: Patrick Kirby
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Patrick Kirby
user_description: I am a Computer Science student studying at Arcadia University. My passions are engineering, programming, and the outdoors!
user_title: Student
email: pjkirby31@gmail.com
github_username:  "https://github.com/pjkirby31"
linkedIn_username: "www.linkedin.com/in/patrick-kirby-379491198"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
